name: aes_256_ecb_pkcs5
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.encryption.aes_256_ecb_pkcs5
        pluginClass: Aes256EcbPkcs5Plugin
      ios:
        pluginClass: Aes256EcbPkcs5Plugin
